apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: democon
    image: michaellihs/secrets-demo:1.0
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: user-pass
            key: username
      - name: PASSWORD_FILE
        value: "/custom/path/pass"
    volumeMounts:
      - name: passvol
        mountPath: "/custom/path"
        readOnly: true
  volumes:
  - name: passvol
    secret:
      secretName: user-pass
      items:
      - key: password
        path: pass
  restartPolicy: Never
