version: "3.1"

services:
  database:
    build:
      context: ./database
    image: michaellihs/mydb:latest
    networks:
    - my_app

  api:
    build:
      context: ./api
    image: michaellihs/myapi:latest
    networks:
    - my_app
    ports:
    - "8081:8080"

  frontend:
    build:
      context: ./ui
    image: michaellihs/myfrontend:latest
    networks:
    - my_app
    ports:
    - "3000:3000"

networks:
  my_app:
